name: socket_audiostream
description: A Windows Flutter plugin for audio recording using Media Foundation.
version: 0.1.1
homepage: https://github.com/dgofman/audiostreamer
repository: https://github.com/dgofman/audiostreamer

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.10.0"

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: SocketAudiostreamPlugin

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^3.0.3
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
